/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import { i18n } from '@kbn/i18n';

// Meta component
export const RULE_EXCEPTION_NAME_LABEL = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.ruleExceptionNameLabel',
  {
    defaultMessage: 'Rule exception name',
  }
);

export const RULE_EXCEPTION_NAME_PLACEHOLDER = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.ruleExceptionNamePlaceholder',
  {
    defaultMessage: 'Name your rule exception',
  }
);

// Conditions component
export const RULE_EXCEPTION_CONDITIONS = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.conditionsTitle',
  {
    defaultMessage: 'Conditions',
  }
);

export const EXCEPTION_BUILDER_INFO = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.infoLabel',
  {
    defaultMessage: "Alerts are generated when the rule's conditions are met, except when:",
  }
);

export const ADD_EXCEPTION_SEQUENCE_WARNING = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.sequenceWarning',
  {
    defaultMessage:
      "This rule's query contains an EQL sequence statement. The exception created will apply to all events in the sequence.",
  }
);

export const OPERATING_SYSTEM_PLACEHOLDER = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.operatingSystemPlaceHolder',
  {
    defaultMessage: 'Select an operating system',
  }
);

// Alert options component
export const CLOSE_ALERTS_SECTION_TITLE = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.closeAlertsTitle',
  {
    defaultMessage: 'Close matching alerts',
  }
);

export const BULK_CLOSE_LABEL_DISABLED = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.bulkCloseLabel.disabled',
  {
    defaultMessage:
      'Close all alerts that match this exception and were generated by this rule (Lists and non-ECS fields are not supported)',
  }
);

export const BULK_CLOSE_LABEL = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.bulkCloseLabel',
  {
    defaultMessage: 'Close all alerts that match this exception and were generated by this rule',
  }
);

export const ENDPOINT_QUARANTINE_TEXT = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.endpointQuarantineText',
  {
    defaultMessage:
      'On all Endpoint hosts, quarantined files that match the exception are automatically restored to their original locations. This exception applies to all rules using Endpoint exceptions.',
  }
);

// Add to lists section
export const ADD_TO_LISTS_SECTION_TITLE = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.addToListsLabel',
  {
    defaultMessage: 'Add to rule or lists',
  }
);

export const ADD_TO_RULE_RADIO_OPTION = (ruleName: string) =>
i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.addToRuleOptionLabel',
  {
    values: { ruleName },
    defaultMessage: 'Add to this rule: {ruleName}',
  }
);

export const ADD_TO_LISTS_OPTION = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.addToListsOptionLabel',
  {
    defaultMessage: 'Add to shared exception lists',
  }
);

export const ADD_TO_LISTS_DESCRIPTION = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.addToListsDescription',
  {
    defaultMessage: 'Select shared exception list to add to. We will make a copy of this exception if multiple lists are selected.',
  }
);

export const ADD_TO_LIST_EMPTY_TITLE = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.addToListEmptyValue',
  {
    defaultMessage: 'No exception lists',
  }
);

export const ADD_TO_LIST_EMPTY_BODY = i18n.translate(
  'xpack.securitySolution.exceptionsFlyout.addToListEmptyValue',
  {
    defaultMessage: "Looks like you don't have any lists. Create a list first to add items to.",
  }
);

export const VIEW_LIST_DETAIL_ACTION = i18n.translate(
  'xpack.securitySolution.eexceptionsFlyout.viewListDetailActionLabel',
  {
    defaultMessage: 'View list detail',
  }
);

export const ERROR_EXCEPTION_LISTS = i18n.translate(
  'xpack.securitySolution.eexceptionsFlyout.errorFetching',
  {
    defaultMessage: 'Error fetching exception lists',
  }
);

export const LOADING_LISTS_MESSAGE = i18n.translate(
  'xpack.securitySolution.eexceptionsFlyout.loadingListsMessage',
  {
    defaultMessage: 'Loading exception lists',
  }
);

export const showSelectedLists = (listsCount: number) =>
  i18n.translate('xpack.securitySolution.eexceptionsFlyout.selectedListsText', {
    defaultMessage: 'Showing {listsCount} {listsCount, plural, =1 {list} other {lists}}',
    values: { listsCount },
  });

// Comments section
export const COMMENTS_SECTION_TITLE = (comments: number) =>
  i18n.translate(
    'xpack.securitySolution.exceptionsFlyout.commentsTitle',
    {
      values: { comments },
      defaultMessage: 'Add comments ({comments})',
    }
  );